### ISSUE TITLE
crash on fenix 3 HR

### ISSUE THREAD

**Issue by danramos79** [werkkrew/ciq-orange-theory#1]
After installing the app, I went to try it out. Launched the app, HR detected, hit enter to start workout, hit enter again after a minute or two, the resume, save, ... screen showed up. Hit enter again to resume but watch would vibrate then reset by itself. Also try hitting back from the workout screen, and it made the watch to reset itself again. Any chance this can be fixed? Thanks.

**Comment by werkkrew** [comment]
I'll take a look, I don't have a Fenix3 HR to test on but I will see if I
can reproduce the issue in the Garmin simulator.

**Comment by danramos79** [comment]
Thanks!

Sent from my iPhone

On Dec 5, 2017, at 1:25 PM, Bryan Chain <notifications@github.com<mailto:notifications@github.com>> wrote:

I'll take a look, I don't have a Fenix3 HR to test on but I will see if I
can reproduce the issue in the Garmin simulator.

**Comment by werkkrew** [comment]
After doing some research it appears the issue is likely related to a bug in the current firmware for that device.

Can you take a look at this thread and see if it appears related:

https://forums.garmin.com/forum/developers/connect-iq/connect-iq-bug-reports/1271079-device-crash-err_log-txt-fenix-3-hr-sw-ver-430-450

**Comment by danramos79** [comment]
It appears to be related. Let’s wait for Garmin to release a firmware update and catch up then. Thank you guys!

Sent from my iPhone

On Dec 13, 2017, at 10:20 AM, Bryan Chain <notifications@github.com<mailto:notifications@github.com>> wrote:


After doing some research it appears the issue is likely related to a bug in the current firmware for that device.

Can you take a look at this thread and see if it appears related:

https://forums.garmin.com/forum/developers/connect-iq/connect-iq-bug-reports/1271079-device-crash-err_log-txt-fenix-3-hr-sw-ver-430-450<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fforums.garmin.com%2Fforum%2Fdevelopers%2Fconnect-iq%2Fconnect-iq-bug-reports%2F1271079-device-crash-err_log-txt-fenix-3-hr-sw-ver-430-450&data=02%7C01%7C%7Ce799ff9cd81b46043c4d08d542455edc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636487788059781480&sdata=FUTsrJeVSO4akMw2R%2BEX1J7IG5lJPmE9MW4SOqEpUhM%3D&reserved=0>
