### ISSUE TITLE
Crash on Vivoactive 4

### ISSUE THREAD

**Issue by egens** [werkkrew/ciq-orange-theory#7]
As people say in the comments app crashes after pressing Enter button on splash screen.
https://apps.garmin.com/en-US/apps/b886d2ac-2f94-4f9d-a7bd-85a59b99e639#0

It shows "IQ" letters with exclamation mark and exits to watch screen.

**Comment by werkkrew** [comment]
I'm sorry this is happening but I am unable to recreate the issue in the Garmin simulator, I am going to release a new version soon that you might consider trying.
