### ISSUE TITLE
Can we keep the workout summary screen?

### ISSUE THREAD

**Issue by pran1990** [werkkrew/ciq-orange-theory#8]
Hi,
First off, thanks a lot for this excellent app! Discovering this was the highlight of my week.

"Upon saving the activity a workout summary screen is displayed. The back or enter button on this screen will exit the app.". From what I can see on garmin connect, the summary screen is thrown away. Is there anyway you can save the summary screen and upload to garmin?

**Comment by werkkrew** [comment]
The workout summary should be uploaded to your garmin app just as it would with any other workout, as far as I know there would be no way to save a screenshot of the summary screen.
